name: Actions 101

on:
  push:
jobs:
  hello_world:
    name: Hello World!
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Run Script
      run: echo Hello, Matt!
  lint:
    name: Swiftlint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Install Swiftlint
      run: |
        brew install swiftlint
        swiftlint autocorrect
        echo Linting done!
