name: Actions 101

on:
  push:
jobs:
  hello_world:
    name: Hello World!
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Script
      run: echo Hello, Matt!
  
  lint:
    name: Swiftlint
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # secrets are added in repo settings
    steps:
#    - uses: act10ns/slack@v1 # use marketplace (3rd party) action https://github.com/marketplace/actions/slack-github-actions-slack-integration
#      with:
#        status: starting
#      if: always()
    - uses: actions/checkout@master
    - name: Install Swiftlint
      id: swiftlint
      run: brew install swiftlint
    - name: Run Swiftlint
      run: swiftlint autocorrect
#    - uses: act10ns/slack@v1
#      with:
#        status: ${{ job.status }}
#        steps: ${{ toJson(steps) }}
#      if: always()

  build:
    name: Build
    runs-on: macos-latest
    needs: lint # don't run if lint step fails
    steps:
    - uses: actions/checkout@master
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Build App
      run: xcodebuild -scheme "ScoreKeeper" -target ScoreKeeper -sdk iphonesimulator clean build
      
  tests:
    name: Run Tests
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Choose Xcode 12 # environment is thrown out between jobs, need to reset environment
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Run Tests
      run: xcodebuild -scheme "ScoreKeeper" -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=14.0' test

# https://codesigning.guide/

  archive:
    name: Archive App
    runs-on: macos-latest
    needs: tests
#    env:
#      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
#    - uses: act10ns/slack@v1
#      with:
#        status: starting
#      if: always()
    - uses: actions/checkout@master
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Decrypt Secrets
      run: ./scripts/decrypt-secrets.sh ${{ secrets.ENCRYPTION_KEY }} ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Create Archive
      run: ./scripts/create-archive.sh
    - name: Export Archive
      run: ./scripts/export-archive.sh
#    - uses: act10ns/slack@v1
#      with:
#        status: ${{ job.status }}
#        steps: ${{ toJson(steps) }}
#      if: always()
